const express=require("express");
const {auth}=require("../middleware/auth");
const allowRoles=require("../middleware/roles");
const c=require("../controllers/test.controller");
const router=express.Router();
router.post("/",auth,allowRoles("INSTITUTE_ADMIN"),c.createTest);
router.get("/manage",auth,allowRoles("INSTITUTE_ADMIN"),c.listInstituteTests);
router.get("/manage/:id",auth,allowRoles("INSTITUTE_ADMIN"),c.getInstituteTest);
router.put("/:id",auth,allowRoles("INSTITUTE_ADMIN"),c.updateInstituteTest);
router.delete("/:id",auth,allowRoles("INSTITUTE_ADMIN"),c.deleteInstituteTest);
router.get("/toppers/latest",auth,allowRoles("INSTITUTE_ADMIN"),c.latestToppers);
router.patch("/:id/deactivate",auth,allowRoles("INSTITUTE_ADMIN"),c.deactivateTest);
router.get("/my",auth,allowRoles("STUDENT"),c.getStudentTests);
router.post("/:id/start",auth,allowRoles("STUDENT"),c.startTest);
router.get("/:id",auth,allowRoles("STUDENT"),c.getTestForStudent);
router.post("/:id/submit",auth,allowRoles("STUDENT"),c.submitTest);
module.exports=router;
